services:
  nuxt:
    build:
      context: .
      dockerfile: docker/nuxt/Dockerfile
    container_name: nuxt
    ports:
      - 3000:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./front:/app:cached
      - nuxt_node_modules:/app/node_modules
    command: sh -c '(npm ci || npm install) && npm run dev'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  go:
    container_name: go
    build:
      context: .
      dockerfile: docker/golang/Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
      - ./backend/golang/src/.env
    depends_on:
      - db
    volumes:
      - ./backend/golang/src:/go/src
      - ./backend/golang/src/internal/images:/go/src/internal/images

volumes:
  nuxt_node_modules: