openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: >-
    A sample API that uses a sample-site as an example to demonstrate features in
    the OpenAPI 3.0 specification
servers:
  - url: 'http://localhost:8003'
paths:
  /users/profile:
    get:
      description: >
        Return user profile
      responses:
        '200':
          description: user profile response
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/UserProfile'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/exercises:
    get:
      summary: Get exercises records for a user by ID)
      description: Numeric ID of the user to get exercises
      responses:
        '200':
          description: A list of exercises
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Exercise'

    post:
      summary: Create a new exercise record for a user by ID 
      requestBody:
        description: Exercise to add to the user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RawExercise'
      responses:
        200:
          description: Successfully created exercise
          content:
              application/json:
                schema:
                  example:
                    code: 200 
                    message: "ok"
  
  /exerciseRecords/{exerciseRecordId}/likes:
    post:
      summary: 運動記録へのいいね
      parameters:
        - in: path
          name: exerciseRecordId
          required: true
          schema: { type: integer }
      responses:
        '204':
          description: like successfully 
        "401":
           description: 未認証
        "500": 
           description: サーバーエラー 
    delete:
      parameters:
        - in: path
          name: exerciseRecordId
          required: true
          schema: { type: integer }
      responses:
        '204':
          description: like successfully 
        "401":
           description: 未認証
        "500": 
           description: サーバーエラー 
    
  /teams:
    get:
      summary: 所属チームのプロフィール
      responses:
        "200":
          description: チーム情報
          content:
            application/json: 
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
    
## 複数レスポンスの例を分離したかっただけなので このエンドポイントは本番環境では利用しないです．
  /users/{userId}/exercises-example:
    get:
      summary: Get exercises records for a user by ID)
      parameters:
        - in: path
          name: userId 
          schema:
            type: integer
            format: "int64"
          required: true
          description: Numeric ID of the user to get exercises
      responses:
        '200':
          description: A list of exercises
          content:
            application/json:
              schema:
                  example:
                    - id: 1
                      imageUrl:  '/images/sportImage.png'
                      time: 45
                      date: "2024-01-01T10:00:00Z"
                      comment: "いい感じに動けた"
                      likesCount: 3
                    - id: 2
                      imageUrl:  '/images/sportImage.png'
                      time: 30
                      date: "2024-01-02T10:00:00Z"
                      comment: "疲れた"
                      likes_count: 0
                    - id: 3
                      imageUrl:  '/images/sportImage.png'
                      time: 60
                      date: "2024-01-03T10:00:00Z"
                      comment: "最高の気分"
                      likesCount: 1
                    - id: 4
                      imageUrl:  '/images/sportImage.png'
                      time: 20
                      date: "2024-01-04T10:00:00Z"
                      comment: "もう少し頑張れたかも"
                      likesCount: 2
                    - id: 5
                      imageUrl:  '/images/sportImage.png'
                      time: 50
                      date: "2024-01-05T10:00:00Z"
                      comment: "楽しかった"
                      likesCount: 2
                    - id: 6
                      imageUrl:  '/images/sportImage.png'
                      time: 40
                      date: "2024-01-06T10:00:00Z"
                      comment: "次はもっと頑張る"
                      likesCount: 1

components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1
        name:
          type: "string"
          example: "Taro"
    
    UserProfile:
      type: "object"
      properties:
        id:
          type: "integer" 
          format: "int64"
          example: 1
        name:
          type: "string"
          example: "Taro"
        profileImage:
          type: "string"
          example: "/images/test.png"        
        followCount:
          type: "integer"
          format: "int64"
          example: 4
        followerCount:
          type: "integer"
          format: "int64"
          example: 60

    Exercise:
      type: "object"
      required:
        - "id" 
        - "imageUrl" 
        - "time" 
      properties:
        id:
          type: "integer"
          format: "int64" 
          example: 1 
        imageUrl:
          type: "integer"
          format: "int64" 
          example:  '/images/sportImage.png'
        time:
          type: "integer"
          format: "int64" 
          example: 45
        date:
          type: "string"
          format: "date-time"
          example: "2024-01-01T10:00:00Z"
        comment:
          type: "string"
          example: "いい感じに動けた"
        likesCount:
          type: "integer"
          example: 3

    RawExercise:
      type: "object" 
      required:
        - "imageUrl" 
        - "time" 
      properties:
        imageUrl:
          type: "integer" 
          format: "int64" 
          example: 1
        time: 
          type: "integer" 
          format: "int64"
          example: 20 
        date:
          type: "string"
          format: "date-time"
          example: "2024-01-01T10:00:00Z"
        comment:
          type: "string"
          example: "いい感じに動けた"
    Team:
      type: "object"
      properties:
        temaName:
          type: string
          description: チーム名
          example: team Dakai
        memberName:
          type: string
          description: チームメンバー
          example: kaito
        memberProfileImage:
          type: string 
          description: 各メンバープロフィール画像 url
          example: /images/test.png
        memberExerciseCount:
          type: integer
          description: メンバーの運動投稿回数
          example: 3

    Error:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
